# Regression 1

### Data Load 

In [1]:
import pandas as pd 
data = pd.read_csv("assignment1.csv")

In [2]:
data

y    x1    x2  x3    x4    x5
0  10  38.9  64.7   4   868  59.7
1  13  41.6  45.3  -4   957  61.4
2  11  39.7  74.1   8   786  61.0
3   7  37.3  48.0  19   984  67.5
4  10  39.5  51.9   6   700  57.2
5   9  37.4  53.6  -5  1037  58.8
6   9  35.1  71.4   3   986  58.6
7   6  38.8  58.3   6   819  59.2
8   5  36.6  52.6 -19   791  54.4

In [3]:
data.shape     # y:(9,1), X:(9,5)

(9, 6)

In [4]:
X = data.drop(["y"], axis=1)
y = data.y

In [5]:
# Matrix 계산을 위해 X와 y를 numpy 형태로 바꾸어줍니다. 
X = X.to_numpy()
y = y.to_numpy()

In [6]:
X

array([[  38.9,   64.7,    4. ,  868. ,   59.7],
       [  41.6,   45.3,   -4. ,  957. ,   61.4],
       [  39.7,   74.1,    8. ,  786. ,   61. ],
       [  37.3,   48. ,   19. ,  984. ,   67.5],
       [  39.5,   51.9,    6. ,  700. ,   57.2],
       [  37.4,   53.6,   -5. , 1037. ,   58.8],
       [  35.1,   71.4,    3. ,  986. ,   58.6],
       [  38.8,   58.3,    6. ,  819. ,   59.2],
       [  36.6,   52.6,  -19. ,  791. ,   54.4]])

In [7]:
y

array([10, 13, 11,  7, 10,  9,  9,  6,  5])

### 1. Normal Equation

## $\hat{\theta} = (X^T\cdot X)^{-1} \cdot X^T \cdot y$

In [8]:
import numpy as np
from numpy.linalg import inv 

In [9]:
def estimate_beta(X, y):
    designX = np.c_[np.ones((9,1)), X]  ### 절편을 구해주기 위해 y의 행만큼을 추가해줌.
    beta_hat = np.linalg.inv(designX.T.dot(designX)).dot(designX.T).dot(y)
    
    return beta_hat

In [10]:
beta_hat = estimate_beta(X, y)
beta_hat

array([-3.92447368e+01,  1.31232583e+00,  8.53744361e-02,  7.41849897e-02,
        1.50018573e-02, -3.42273652e-01])

### Compare $\hat{y}$ with y

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
model = LinearRegression()
model.fit(X, y)

pred = model.predict(X)
pred

array([10.21307892, 12.25991477, 10.68709119,  6.87086032,  8.39142371,
        9.47262921,  7.8707847 ,  9.11986574,  5.11435143])

In [13]:
print(model.intercept_)   # intercept
print(model.coef_)   # 추정된 회귀계수 (intercept 제외)

-39.24473678135655
[ 1.31232583  0.08537444  0.07418499  0.01500186 -0.34227365]


### 2. MSE

### $ MSE = \sum(y-\hat{y})^{2}$ 

In [24]:
def MSE(X, y, beta_hat):
    designX = np.c_[np.ones((9,1)), X]  
    y_pred = designX.dot(beta_hat)
    mse = (sum(np.square(y-y_pred))) / 3 # n(관측치의 개수) - p(설명변수의 개수)
    
    return mse

In [25]:
MSE(X, y, estimate_beta(X, y))

4.846793168705742